### ISSUE TITLE
大佬，如果有空的时候能不能请教一下P站用户作品是怎么获取的呢？

### ISSUE THREAD

**Issue by snowyue** [darkchii/pixiver#4]
大佬，好像 如果是一个作品有多张图片 只会下载第一张？

**Comment by darkchii** [comment]
是的  我之前就想把这个弄了 而且也不麻烦 但太懒了(扶額

**Comment by darkchii** [comment]
关于用户作品的获取原理其实就是这个接口：https://www.pixiv.net/ajax/user/p站用户ID/profile/all        访问接口可以看到 json

**Comment by snowyue** [comment]
其实数量就包涵在rank的json里面。我在json里面找到了，不过 我不会登录 读取数据 有点烦，
   QJsonValue arrays_value = jsonObject["contents"].toArray();

               QString title = icon["title"].toString();//图片标题
               QString date = icon["date"].toString();//时间
               QString tags = icon["tags"].toString();//标签

               QString user_name = icon["user_name"].toString();//用户名
               QString user_id = icon["user_id"].toString();//用户ID+
               QString illust_id = icon["illust_id"].toString();//图片id
               QString height = icon["height"].toString();//图片高度
               QString width = icon["width"].toString();//图片宽度
               QString illust_page_count = icon["illust_page_count"].toString();//图片数量
我之前用的qt，也能读取，不过 要登陆才能下载，我就没写了

**Comment by snowyue** [comment]
然后，大佬 请问登录信息可以保存吗？我登陆了好几次然后打不开登录页面了。我还以为我被banip了

**Comment by darkchii** [comment]
P站普通图片不需要登录就可以下载的
登录信息当然可以保存呀 就是 cookie 嘛  但网页版的登录我也没能完全模拟成功   我看另一个大佬的解决办法是模拟登录app获取的

**Comment by snowyue** [comment]
P站图片 我试过 加一个头部可以不用登录下载，不登陆的话原图获取不到 因为有的是png，jpg

**Comment by darkchii** [comment]
不用登录的
https://www.pixiv.net/ajax/illust/作品ID
这个接口可以获取到原图链接  就可以得到原图格式

**Comment by snowyue** [comment]
这么神奇的么大佬，我先试试谢谢 大佬

**Comment by darkchii** [comment]
抱歉啊  下午还要工作  到现在才回复您

**Comment by snowyue** [comment]
客气，我请教问题 等大佬有空是应该的

**Comment by darkchii** [comment]
哇  惊了  竟然还在吗 秒回呀  哈哈（｡ò ∀ ó｡）

**Comment by snowyue** [comment]
我这边有点事情，暂时没睡  我一般比较晚睡

**Comment by darkchii** [comment]
哦哦 有什么问题你可以加我qq 906835882 一起探讨交流  记得备注一下github id

**Comment by snowyue** [comment]
好的，等我忙完了 就加一下
